### ISSUE TITLE
Home-Assistant Integration

### ISSUE THREAD

**Issue by thundergreen** [nygma2004/beca_mqtt#2]
Hi Fella. I saw your Youtube-Vdeo and I am amazed and curious if it's possible to add this in Home-Assistant. I thought I did see a screen with Home-Assistant right?

My Idea is to place those Thermostats in each room to control my AC.

My AC are controlled by Xiaomi IR extenders and a custom Component. Now I'd like to somehow fiddle this together. Means. Homeassistant will create the Climate conponent and then i somehow have to bridge those received and sent mqtt topics to control my xiaomi ac custom component. Do you think it's makeable?

**Comment by nygma2004** [comment]
I don't have Home Assistant, and the screen you have seen is Node-Red. The UI is very similar to HA. But I think it could be done. HA also works with any device over MQTT. So you should be able to integrated it. I am not sure about the xiaomi part though.

**Comment by thundergreen** [comment]
Ok..sounds good .. I'll give it a shot and you're right ..I'm also running
some stuff on nodered for home-assistant. Which model is it exactly for the
thermostat?

Thanks a lot for your answer and I'll revert to you asap

nygma2004 <notifications@github.com> schrieb am Do., 7. Nov. 2019, 08:58:

**Comment by nygma2004** [comment]
Mine was the 2 pipe version with modbus. But they sell all possible combination. So decide which version you need and just look for the modbus version. I don't think they are selling all combination on Amazon, but you will find all models on http://becaenergy.com/.
