### ISSUE TITLE
State all the libraries

### ISSUE THREAD

**Issue by ngalfas** [nygma2004/beca_mqtt#3]
Hi, just trying your code.  I saw the README stating 2 libraries. 
ModbusMaster  which needs to be added to the Arduino IDE and EspSoftware Special which is already  available when ESP8266 installs its board package.

Also there are some more libraries need to be installed.
PubSubClient, Time and sunMoon.

The first two i found on the Libraries Manager.  
I can't find the sunMoon Library. There is no such library on the Manager. 
Even searched for it but still not sure.  
Maybe you can clarify this and add these to the README?

**Comment by ngalfas** [comment]
when i had a better look on the code, i saw you commented all the daylight calculations. 
so i just removed all of the sunMoon references from the code.

**Comment by nygma2004** [comment]
Sorry for the slow response. I have updated the readme.
